import * as pdfjs from "./vendor/pdf.min.mjs";
pdfjs.GlobalWorkerOptions.workerSrc="./vendor/pdf.worker.min.mjs";
const $=id=>document.getElementById(id), canvas=$("canvas"),ctx=canvas.getContext("2d");
const colors=["#17262e","#dd5f7c","#f39a22","#e6cc35","#2da66f","#2687d7","#7555c7","#ffffff"];
let tool="pen",color="#dd5f7c",size=6,fontSize=36,hasDoc=false,start=null,drawing=false,base=null,history=[],hi=-1,folderFiles=[],folderIndex=0,installPrompt=null;
function save(){history=history.slice(0,hi+1);history.push(ctx.getImageData(0,0,canvas.width,canvas.height));if(history.length>25)history.shift();hi=history.length-1}
function restore(i){if(history[i]){ctx.putImageData(history[i],0,0);hi=i}}
function point(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
function setup(){ctx.lineCap=ctx.lineJoin="round";ctx.strokeStyle=tool==="eraser"?"#fff":color;ctx.fillStyle=color;ctx.lineWidth=tool==="eraser"?size*3:size}
canvas.onpointerdown=e=>{if(!hasDoc)return;canvas.setPointerCapture(e.pointerId);let p=point(e);if(tool==="text"){let t=$("text").value.trim();if(!t)return status("Escribe primero el texto");setup();ctx.font=`700 ${fontSize}px Arial`;ctx.textBaseline="top";ctx.fillText(t,p.x,p.y);save();return}drawing=true;start=p;base=document.createElement("canvas");base.width=canvas.width;base.height=canvas.height;base.getContext("2d").drawImage(canvas,0,0);setup();ctx.beginPath();ctx.moveTo(p.x,p.y)};
canvas.onpointermove=e=>{if(!drawing)return;let p=point(e);setup();if(tool==="pen"||tool==="eraser"){ctx.lineTo(p.x,p.y);ctx.stroke();return}ctx.drawImage(base,0,0);ctx.beginPath();if(tool==="line"){ctx.moveTo(start.x,start.y);ctx.lineTo(p.x,p.y)}else ctx.ellipse((start.x+p.x)/2,(start.y+p.y)/2,Math.abs(p.x-start.x)/2,Math.abs(p.y-start.y)/2,0,0,Math.PI*2);ctx.stroke()};
canvas.onpointerup=canvas.onpointercancel=()=>{if(drawing){drawing=false;start=base=null;save()}};
function status(s){$("status").textContent=s}
function showDoc(name){hasDoc=true;$("empty").hidden=true;canvas.classList.add("show");$("fileName").textContent=name;["png","pdf","change","remove"].forEach(id=>$(id).disabled=false);$("change").hidden=$("remove").hidden=false;history=[];hi=-1;save()}
async function load(file,pos){status("Preparando…");try{if(file.type==="application/pdf"||file.name.toLowerCase().endsWith(".pdf")){let pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,page=await pdf.getPage(1),v0=page.getViewport({scale:1}),scale=Math.min(1600/v0.width,1200/v0.height,2),v=page.getViewport({scale});canvas.width=Math.round(v.width);canvas.height=Math.round(v.height);ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);await page.render({canvasContext:ctx,viewport:v}).promise}else await new Promise((ok,no)=>{let im=new Image(),url=URL.createObjectURL(file);im.onload=()=>{let s=Math.min(1600/im.width,1200/im.height,1);canvas.width=Math.round(im.width*s);canvas.height=Math.round(im.height*s);ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(im,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);ok()};im.onerror=no;im.src=url});showDoc(file.name);status(pos?`Archivo ${pos.current} de ${pos.total} · listo para marcar`:"Listo para marcar")}catch{status("No se pudo abrir. Usa PDF o una imagen.")}}
function input(id,folder=false){$(id).onchange=async e=>{let files=[...e.target.files].filter(f=>f.type.startsWith("image/")||f.type==="application/pdf"||f.name.toLowerCase().endsWith(".pdf"));if(!files.length)return;if(folder){folderFiles=files;folderIndex=0;$("folderNav").hidden=files.length<2;updateFolder();await load(files[0],{current:1,total:files.length})}else{folderFiles=[];$("folderNav").hidden=true;await load(files[0])}e.target.value=""}}
input("fileInput");input("cameraInput");input("folderInput",true);
function updateFolder(){$("folderCount").textContent=`${folderIndex+1}/${folderFiles.length}`;$("prev").disabled=folderIndex===0;$("next").disabled=folderIndex===folderFiles.length-1}
async function move(d){let n=folderIndex+d;if(n<0||n>=folderFiles.length)return;folderIndex=n;updateFolder();await load(folderFiles[n],{current:n+1,total:folderFiles.length})}
$("prev").onclick=()=>move(-1);$("next").onclick=()=>move(1);
["choose","openTop","change"].forEach(id=>$(id).onclick=()=>$("fileInput").click());$("camera").onclick=()=>$("cameraInput").click();$("folder").onclick=()=>$("folderInput").click();
$("blank").onclick=()=>{canvas.width=1200;canvas.height=780;ctx.fillStyle="#fff";ctx.fillRect(0,0,1200,780);showDoc("hoja-en-blanco");status("Hoja en blanco lista")};
$("remove").onclick=()=>{hasDoc=false;$("empty").hidden=false;canvas.classList.remove("show");$("fileName").textContent="Sin archivo";status("Archivo eliminado. Elige otro.");["png","pdf"].forEach(id=>$(id).disabled=true);$("change").hidden=$("remove").hidden=true;$("folderNav").hidden=true};
$("tools").onclick=e=>{let b=e.target.closest("[data-tool]");if(!b)return;tool=b.dataset.tool;document.querySelectorAll("[data-tool]").forEach(x=>x.classList.toggle("active",x===b));$("textBox").hidden=tool!=="text"};
const colorBox=$("colors");colors.forEach(c=>{let b=document.createElement("button");b.style.background=c;b.onclick=()=>{color=c;document.querySelectorAll("#colors button").forEach(x=>x.classList.toggle("selected",x===b))};colorBox.append(b)});colorBox.children[1].classList.add("selected");
$("customColor").oninput=e=>color=e.target.value;$("size").oninput=e=>{size=+e.target.value;$("sizeOut").value=size};$("fontSize").oninput=e=>{fontSize=+e.target.value;$("fontOut").value=fontSize};
$("undo").onclick=()=>{if(hi>0)restore(hi-1)};$("redo").onclick=()=>{if(hi<history.length-1)restore(hi+1)};
$("png").onclick=()=>{let a=document.createElement("a");a.download="fotos-marcado.png";a.href=canvas.toDataURL();a.click()};
$("pdf").onclick=()=>{let {jsPDF}=window.jspdf,p=new jsPDF({orientation:canvas.width>=canvas.height?"landscape":"portrait",unit:"px",format:[canvas.width,canvas.height]});p.addImage(canvas.toDataURL("image/jpeg",.95),"JPEG",0,0,canvas.width,canvas.height);p.save("fotos-marcado.pdf")};
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e});$("install").onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null}else $("installHelp").showModal()};document.querySelector(".close").onclick=()=>$("installHelp").close();
ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");
