import * as pdfjs from "./vendor/pdf.min.mjs";
pdfjs.GlobalWorkerOptions.workerSrc="./vendor/pdf.worker.min.mjs";
const $=id=>document.getElementById(id), canvas=$("canvas"),ctx=canvas.getContext("2d"),stage=document.querySelector(".stage");
const colors=["#17262e","#dd5f7c","#f39a22","#e6cc35","#2da66f","#2687d7","#7555c7","#ffffff"];
let tool="pen",color="#dd5f7c",size=6,fontSize=36,hasDoc=false,start=null,drawing=false,base=null,history=[],hi=-1,folderFiles=[],folderIndex=0,zoom=1,pointers=new Map(),pinch=null,panStart=null;
function save(){history=history.slice(0,hi+1);history.push(ctx.getImageData(0,0,canvas.width,canvas.height));if(history.length>25)history.shift();hi=history.length-1}
function restore(i){if(history[i]){ctx.putImageData(history[i],0,0);hi=i}}
function point(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
function setup(){ctx.lineCap=ctx.lineJoin="round";ctx.strokeStyle=tool==="eraser"?"#fff":color;ctx.fillStyle=color;ctx.lineWidth=tool==="eraser"?size*3:size}
canvas.onpointerdown=e=>{if(!hasDoc)return;canvas.setPointerCapture(e.pointerId);let p=point(e);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){if(base)ctx.drawImage(base,0,0);drawing=false;let [a,b]=[...pointers.values()],r=stage.getBoundingClientRect();pinch={distance:Math.hypot(b.x-a.x,b.y-a.y),zoom,centerX:(a.x+b.x)/2-r.left,centerY:(a.y+b.y)/2-r.top,scrollLeft:stage.scrollLeft,scrollTop:stage.scrollTop};return}if(tool==="pan"){panStart={x:e.clientX,y:e.clientY,scrollLeft:stage.scrollLeft,scrollTop:stage.scrollTop};drawing=false;return}if(tool==="text"){let t=$("text").value.trim();if(!t)return status("Escribe primero el texto");setup();ctx.font=`700 ${fontSize}px Arial`;ctx.textBaseline="top";ctx.fillText(t,p.x,p.y);save();return}drawing=true;start=p;base=document.createElement("canvas");base.width=canvas.width;base.height=canvas.height;base.getContext("2d").drawImage(canvas,0,0);setup();ctx.beginPath();ctx.moveTo(p.x,p.y)};
canvas.onpointermove=e=>{if(pointers.has(e.pointerId))pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size>=2&&pinch){let [a,b]=[...pointers.values()],d=Math.hypot(b.x-a.x,b.y-a.y),nextZoom=Math.min(5,Math.max(.5,pinch.zoom*d/pinch.distance)),r=stage.getBoundingClientRect(),currentX=(a.x+b.x)/2-r.left,currentY=(a.y+b.y)/2-r.top,ratio=nextZoom/pinch.zoom;setZoom(nextZoom);stage.scrollLeft=(pinch.scrollLeft+pinch.centerX)*ratio-currentX;stage.scrollTop=(pinch.scrollTop+pinch.centerY)*ratio-currentY;return}if(tool==="pan"&&panStart){stage.scrollLeft=panStart.scrollLeft-(e.clientX-panStart.x);stage.scrollTop=panStart.scrollTop-(e.clientY-panStart.y);return}if(!drawing)return;let p=point(e);setup();if(tool==="pen"||tool==="eraser"){ctx.lineTo(p.x,p.y);ctx.stroke();return}ctx.drawImage(base,0,0);ctx.beginPath();if(tool==="line"){ctx.moveTo(start.x,start.y);ctx.lineTo(p.x,p.y)}else ctx.ellipse((start.x+p.x)/2,(start.y+p.y)/2,Math.abs(p.x-start.x)/2,Math.abs(p.y-start.y)/2,0,0,Math.PI*2);ctx.stroke()};
canvas.onpointerup=canvas.onpointercancel=e=>{pointers.delete(e.pointerId);panStart=null;if(pinch){if(pointers.size<2)pinch=null;drawing=false;start=base=null;return}if(drawing){drawing=false;start=base=null;save()}};
function status(s){$("status").textContent=s}
function setZoom(value){zoom=Math.min(5,Math.max(.5,value));canvas.style.width=`${zoom*100}%`;canvas.style.justifySelf=zoom>1?"start":"center";$("zoomValue").textContent=`${Math.round(zoom*100)}%`}
function showDoc(name){hasDoc=true;setZoom(1);$("empty").hidden=true;$("zoomControls").hidden=false;canvas.classList.add("show");$("fileName").textContent=name;["share","png","pdf","change","remove"].forEach(id=>$(id).disabled=false);$("openTop").hidden=false;$("change").hidden=$("remove").hidden=false;history=[];hi=-1;save()}
async function load(file,pos){status("Preparando…");try{if(file.type==="application/pdf"||file.name.toLowerCase().endsWith(".pdf")){let pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,page=await pdf.getPage(1),v0=page.getViewport({scale:1}),scale=Math.min(1600/v0.width,1200/v0.height,2),v=page.getViewport({scale});canvas.width=Math.round(v.width);canvas.height=Math.round(v.height);ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);await page.render({canvasContext:ctx,viewport:v}).promise}else await new Promise((ok,no)=>{let im=new Image(),url=URL.createObjectURL(file);im.onload=()=>{let s=Math.min(1600/im.width,1200/im.height,1);canvas.width=Math.round(im.width*s);canvas.height=Math.round(im.height*s);ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(im,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);ok()};im.onerror=no;im.src=url});showDoc(file.name);status(pos?`Archivo ${pos.current} de ${pos.total} · listo para marcar`:"Listo para marcar")}catch{status("No se pudo abrir. Usa PDF o una imagen.")}}
function input(id,folder=false){$(id).onchange=async e=>{let files=[...e.target.files].filter(f=>f.type.startsWith("image/")||f.type==="application/pdf"||f.name.toLowerCase().endsWith(".pdf"));if(!files.length)return;if(folder){folderFiles=files;folderIndex=0;$("folderNav").hidden=files.length<2;updateFolder();await load(files[0],{current:1,total:files.length})}else{folderFiles=[];$("folderNav").hidden=true;await load(files[0])}e.target.value=""}}
input("fileInput");input("cameraInput");input("folderInput",true);
function updateFolder(){$("folderCount").textContent=`${folderIndex+1}/${folderFiles.length}`;$("prev").disabled=folderIndex===0;$("next").disabled=folderIndex===folderFiles.length-1}
async function move(d){let n=folderIndex+d;if(n<0||n>=folderFiles.length)return;folderIndex=n;updateFolder();await load(folderFiles[n],{current:n+1,total:folderFiles.length})}
$("prev").onclick=()=>move(-1);$("next").onclick=()=>move(1);
["choose","openTop","change"].forEach(id=>$(id).onclick=()=>$("fileInput").click());$("camera").onclick=()=>$("cameraInput").click();$("folder").onclick=()=>$("folderInput").click();
$("blank").onclick=()=>{canvas.width=1200;canvas.height=780;ctx.fillStyle="#fff";ctx.fillRect(0,0,1200,780);showDoc("hoja-en-blanco");status("Hoja en blanco lista")};
$("remove").onclick=()=>{hasDoc=false;setZoom(1);pointers.clear();pinch=null;$("empty").hidden=false;$("zoomControls").hidden=true;canvas.classList.remove("show");$("fileName").textContent="Sin archivo";status("Archivo eliminado. Elige otro.");["share","png","pdf"].forEach(id=>$(id).disabled=true);$("openTop").hidden=true;$("change").hidden=$("remove").hidden=true;$("folderNav").hidden=true};
$("tools").onclick=e=>{let b=e.target.closest("[data-tool]");if(!b)return;tool=b.dataset.tool;canvas.style.cursor=tool==="pan"?"grab":"crosshair";document.querySelectorAll("[data-tool]").forEach(x=>x.classList.toggle("active",x===b));$("textBox").hidden=tool!=="text"};
const colorBox=$("colors"),customColor=$("customColor");colors.forEach(c=>{let b=document.createElement("button");b.style.background=c;b.onclick=()=>{color=c;document.querySelectorAll("#colors button").forEach(x=>x.classList.toggle("selected",x===b))};colorBox.insertBefore(b,customColor)});document.querySelectorAll("#colors button")[1].classList.add("selected");
$("customColor").oninput=e=>color=e.target.value;$("size").oninput=e=>{size=+e.target.value;$("sizeOut").value=size};$("fontSize").oninput=e=>{fontSize=+e.target.value;$("fontOut").value=fontSize};
$("undo").onclick=()=>{if(hi>0)restore(hi-1)};$("redo").onclick=()=>{if(hi<history.length-1)restore(hi+1)};
$("png").onclick=()=>{let a=document.createElement("a");a.download="fotos-marcado.png";a.href=canvas.toDataURL();a.click()};
$("pdf").onclick=()=>{let {jsPDF}=window.jspdf,p=new jsPDF({orientation:canvas.width>=canvas.height?"landscape":"portrait",unit:"px",format:[canvas.width,canvas.height]});p.addImage(canvas.toDataURL("image/jpeg",.95),"JPEG",0,0,canvas.width,canvas.height);p.save("fotos-marcado.pdf")};
$("share").onclick=async()=>{let blob=await new Promise(ok=>canvas.toBlob(ok,"image/png")),file=new File([blob],"fotos-marcado.png",{type:"image/png"}),data={title:"Foto modificada",text:"Imagen editada con Fotos",files:[file]};try{if(navigator.canShare?.(data)){await navigator.share(data);status("Imagen compartida")}else{status("Tu navegador no permite compartir archivos. Descargando…");$("png").click()}}catch(e){if(e.name!=="AbortError")status("No se pudo compartir la imagen")}};
$("zoomOut").onclick=()=>setZoom(zoom-.25);$("zoomIn").onclick=()=>setZoom(zoom+.25);$("zoomValue").onclick=()=>setZoom(1);
ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");
